### 1437
openapi: 3.0.3
info:
  title: RNGE API
  version: 1.0.0

servers:
  - url: 'https://homolog.rnge.com.br/v2'
    description: Homologação
  - url: 'https://rnge.com.br/v2'
    description: Produção

paths:
# ../v2api/api/v2cashiers.go
  /cashiers:
# modelo = TabelaPontoVenda
    post:
      summary: Cria um(a) cashiers
# ../v2api/api/v2charts.go
  /charts:
# modelo = 
    get:
      summary: Listagem de charts
# ../v2api/api/v2tokens.go
  /tokens:
# filtros = FilterTokens
# modelo = JSONToken
    get:
      summary: Listagem de tokens
# ../v2api/api/v2users.go
  /users:
# modelo = JSONUser
    post:
      summary: Cria um(a) users
# ../v2api/api/v2users.go
  /users/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do users
# modelo = JSONUser
    put:
      summary: Atualiza um(a) users
    delete:
      summary: Deleta um(a) users
# ../v2api/api/v2prospects.go
  /prospects:
# filtros = FilterProspects
# modelo = JSONProspect
    get:
      summary: Listagem de prospects
# ../v2api/api/v2cashiers.go
  /cashiers/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do cashiers
# modelo = TabelaPontoVenda
    delete:
      summary: Deleta um(a) cashiers
# ../v2api/api/v2metrics.go
  /metrics:
# filtros = FilterMetrics
# modelo = JSONIndicadoresV2
    get:
      summary: Listagem de metrics
# ../v2api/api/v2metrics.go
  /metrics/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do metrics
# modelo = JSONIndicadoresV2
    put:
      summary: Atualiza um(a) metrics
    delete:
      summary: Deleta um(a) metrics
# ERRO open ../v2api/api/v2me.go: no such file or directory
# ../v2api/api/v2tokens.go
  /tokens/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do tokens
# modelo = JSONToken
    put:
      summary: Atualiza um(a) tokens
    delete:
      summary: Deleta um(a) tokens
# ../v2api/api/v2prospects.go
  /prospects/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do prospects
# modelo = JSONProspect
    get:
      summary: Busca um(a) prospects
      responses:
        '200':
          description: prospects
          content:
            application/json:
              schema:
                $ref: docs/models/jsonprospect.yaml
# ../v2api/api/v2menu.go
  /menu:
# modelo = 
    get:
      summary: Listagem de menu
# ../v2api/api/v2logout.go
  /logout:
# modelo = 
    post:
      summary: Cria um(a) logout
