openapi: 3.0.3
info:
  title: RNGE API
  version: 1.0.0

servers:
  - url: 'https://homolog.rnge.com.br/v2'
    description: Homologação
  - url: 'https://rnge.com.br/v2'
    description: Produção

paths:
### ("/v2/prospects", authToken(api.ProspectsGet)).Methods(http.MethodGet)
### ("/v2/prospects/{id:[0-9]+}", authToken(api.ProspectsGet)).Methods(http.MethodGet)
### ("/v2/menu", authToken(api.MenuGet)).Methods(http.MethodGet)
### ("/v2/logout", authToken(api.LogoutPost)).Methods(http.MethodPost)
### ("/v2/cashiers", authToken(api.CashiersGet)).Methods(http.MethodGet)
### ("/v2/cashiers", authToken(api.CashiersPostPut)).Methods(http.MethodPost)
### ("/v2/cashiers/{pdv_id:[0-9]+}", authToken(api.CashiersGet)).Methods(http.MethodGet)
### ("/v2/cashiers/{pdv_id:[0-9]+}", authToken(api.CashiersPostPut)).Methods(http.MethodPut)
### ("/v2/cashiers/{pdv_id:[0-9]+}", authToken(api.CashiersDelete)).Methods(http.MethodDelete)
### ("/v2/metrics", authToken(api.MetricsGet)).Methods(http.MethodGet)
### ("/v2/metrics/{id:[0-9]+}", authToken(api.MetricsGet)).Methods(http.MethodGet)
### ("/v2/metrics/{id:[0-9]+}", authToken(api.MetricsPostPutDelete)).Methods(http.MethodPut, http.MethodDelete)
### ("/v2/charts", authToken(api.ChartsGet)).Methods(http.MethodGet)
### ("/v2/tokens", authToken(api.TokensGet)).Methods(http.MethodGet)
### ("/v2/me", authToken(api.TokensGet)).Methods(http.MethodGet) //--- GET v2/tokens/{id} do usuário logado
### ("/v2/tokens/{id:[0-9]+}", authToken(api.TokensGet)).Methods(http.MethodGet)
### ("/v2/tokens/{id:[0-9]+}", authToken(api.TokensPutDelete)).Methods(http.MethodPut, http.MethodDelete)
### ("/v2/users", authToken(api.UsersGet)).Methods(http.MethodGet)
### ("/v2/users/{id:[0-9]+}", authToken(api.UsersGet)).Methods(http.MethodGet)
### ("/v2/users", authToken(api.UsersPostPutDelete)).Methods(http.MethodPost)
### ("/v2/users/{id:[0-9]+}", authToken(api.UsersPostPutDelete)).Methods(http.MethodPut, http.MethodDelete)
# ../v2api/api/v2menu.go
  /menu:
    get:
      summary: Listagem de menu
# modelo = 
# ../v2api/api/v2cashiers.go
  /cashiers:
    post:
      summary: Cria um(a) cashiers
# modelo = TabelaPontoVenda
# ../v2api/api/v2metrics.go
  /metrics/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do metrics
    put:
      summary: Atualiza um(a) metrics
    delete:
      summary: Deleta um(a) metrics
# modelo = JSONIndicadoresV2
# ../v2api/api/v2charts.go
  /charts:
    get:
      summary: Listagem de charts
# modelo = 
# ../v2api/api/v2logout.go
  /logout:
    post:
      summary: Cria um(a) logout
# modelo = 
# ../v2api/api/v2cashiers.go
  /cashiers/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do cashiers
    delete:
      summary: Deleta um(a) cashiers
# modelo = TabelaPontoVenda
# ../v2api/api/v2metrics.go
  /metrics:
    get:
      summary: Listagem de metrics
# filtros = FilterMetrics
# modelo = JSONIndicadoresV2
# ../v2api/api/v2tokens.go
  /tokens:
    get:
      summary: Listagem de tokens
# filtros = FilterTokens
# modelo = JSONToken
# ERRO open ../v2api/api/v2me.go: no such file or directory
# ../v2api/api/v2tokens.go
  /tokens/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do tokens
    put:
      summary: Atualiza um(a) tokens
    delete:
      summary: Deleta um(a) tokens
# modelo = JSONToken
# ../v2api/api/v2users.go
  /users:
    post:
      summary: Cria um(a) users
# modelo = JSONUser
# ../v2api/api/v2users.go
  /users/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do users
    put:
      summary: Atualiza um(a) users
    delete:
      summary: Deleta um(a) users
# modelo = JSONUser
# ../v2api/api/v2prospects.go
  /prospects:
    get:
      summary: Listagem de prospects
# filtros = FilterProspects
# modelo = JSONProspect
# ../v2api/api/v2prospects.go
  /prospects/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do prospects
    get:
      summary: Busca um(a) prospects
# modelo = JSONProspect
