### 1437
openapi: 3.0.3
info:
  title: RNGE API
  version: 1.0.0

servers:
  - url: 'https://homolog.rnge.com.br/v2'
    description: Homologação
  - url: 'https://rnge.com.br/v2'
    description: Produção

tags:
  - name: Cashiers
    description: Cashiers
  - name: Charts
    description: Charts
  - name: Logout
    description: Logout
  - name: Me
    description: Me
  - name: Menu
    description: Menu
  - name: Metrics
    description: Metrics
  - name: Order5929
    description: Order5929
  - name: Orderimport
    description: Orderimport
  - name: Orderitems
    description: Orderitems
  - name: Orders
    description: Orders
  - name: Orderstatus
    description: Orderstatus
  - name: Productimages
    description: Productimages
  - name: Prospects
    description: Prospects
  - name: Serviceorderitems
    description: Serviceorderitems
  - name: Serviceorders
    description: Serviceorders
  - name: Tokens
    description: Tokens
  - name: Users
    description: Users

paths:
# ../v2api/api/v2cashiers.go
  /cashiers:
# modelo = TabelaPontoVenda
    post:
      tags:
       - Cashiers
      summary: Cria um(a) cashiers
      responses:
        '200':
          description: cashiers
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/tabelapontovenda.yaml
# ../v2api/api/v2cashiers.go
  /cashiers/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do cashiers
# modelo = TabelaPontoVenda
    delete:
      tags:
       - Cashiers
      summary: Deleta um(a) cashiers
# ../v2api/api/v2charts.go
  /charts:
# modelo = 
    get:
      tags:
       - Charts
      summary: Listagem de charts
      responses:
        '200':
          description: charts
# ../v2api/api/v2logout.go
  /logout:
# modelo = 
    post:
      tags:
       - Logout
      summary: Cria um(a) logout
      responses:
        '200':
          description: logout
# ERRO open ../v2api/api/v2me.go: no such file or directory
# ../v2api/api/v2menu.go
  /menu:
# modelo = 
    get:
      tags:
       - Menu
      summary: Listagem de menu
      responses:
        '200':
          description: menu
# ../v2api/api/v2metrics.go
  /metrics:
# filtros = FilterMetrics
# modelo = JSONIndicadoresV2
    get:
      tags:
       - Metrics
      summary: Listagem de metrics
      responses:
        '200':
          description: metrics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/jsonindicadoresv2.yaml
# ../v2api/api/v2metrics.go
  /metrics/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do metrics
# modelo = JSONIndicadoresV2
    put:
      tags:
       - Metrics
      summary: Atualiza um(a) metrics
    delete:
      tags:
       - Metrics
      summary: Deleta um(a) metrics
# ERRO open ../v2api/api/v2order5929.go: no such file or directory
# ERRO open ../v2api/api/v2ordercancel.go: no such file or directory
# ERRO open ../v2api/api/v2orderdraft.go: no such file or directory
# ERRO open ../v2api/api/v2orderimport.go: no such file or directory
# ERRO open ../v2api/api/v2orderitems.go: no such file or directory
# ERRO open ../v2api/api/v2orderitems.go: no such file or directory
# ../v2api/api/v2orders.go
  /orders:
# modelo = JSONOrder
    post:
      tags:
       - Orders
      summary: Cria um(a) orders
      responses:
        '200':
          description: orders
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/jsonorder.yaml
# ../v2api/api/v2orders.go
  /orders/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do orders
# modelo = JSONOrder
    patch:
      tags:
       - Orders
# ERRO open ../v2api/api/v2orderstatus.go: no such file or directory
# ERRO open ../v2api/api/v2orderstatus.go: no such file or directory
# ERRO open ../v2api/api/v2ordersync.go: no such file or directory
# ERRO open ../v2api/api/v2productimages.go: no such file or directory
# ERRO open ../v2api/api/v2productimages.go: no such file or directory
# ../v2api/api/v2profiles.go
  /profiles/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do profiles
# modelo = JSONProfile
    put:
      tags:
       - Profiles
      summary: Atualiza um(a) profiles
# ../v2api/api/v2prospects.go
  /prospects:
# filtros = FilterProspects
# modelo = JSONProspect
    get:
      tags:
       - Prospects
      summary: Listagem de prospects
      responses:
        '200':
          description: prospects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/jsonprospect.yaml
# ../v2api/api/v2prospects.go
  /prospects/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do prospects
# modelo = JSONProspect
    get:
      tags:
       - Prospects
      summary: Busca um(a) prospects
      responses:
        '200':
          description: prospects
          content:
            application/json:
              schema:
                $ref: ./models/jsonprospect.yaml
# ERRO open ../v2api/api/v2serviceorderitems.go: no such file or directory
# ERRO open ../v2api/api/v2serviceorders.go: no such file or directory
# ERRO open ../v2api/api/v2serviceorders.go: no such file or directory
# ../v2api/api/v2tokens.go
  /tokens:
# filtros = FilterTokens
# modelo = JSONToken
    get:
      tags:
       - Tokens
      summary: Listagem de tokens
      responses:
        '200':
          description: tokens
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/jsontoken.yaml
# ../v2api/api/v2tokens.go
  /tokens/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do tokens
# modelo = JSONToken
    put:
      tags:
       - Tokens
      summary: Atualiza um(a) tokens
    delete:
      tags:
       - Tokens
      summary: Deleta um(a) tokens
# ../v2api/api/v2users.go
  /users:
# modelo = JSONUser
    post:
      tags:
       - Users
      summary: Cria um(a) users
      responses:
        '200':
          description: users
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/jsonuser.yaml
# ../v2api/api/v2users.go
  /users/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID do users
# modelo = JSONUser
    put:
      tags:
       - Users
      summary: Atualiza um(a) users
    delete:
      tags:
       - Users
      summary: Deleta um(a) users
